[package]
name = "textenc"
version = "0.1.0"
edition = "2021"

[dependencies]
aes = "0.8.4"
anyhow = "1.0.95"
clap = {version = "4.5.23", features = ["derive"]}
ctr = "0.9.2"
hex = "0.4.3"
scrypt = "0.11.0"
serde = {version = "1.0.216", features = ["derive"]}
serde_json = "1.0.134"
sha3 = "0.10.8"
