[package]
name = "textenclib"
version = "0.1.0"
edition = "2021"

[dependencies]
aes = "0.8.4"
anyhow = "1.0.98"
ctr = "0.9.2"
hex = "0.4.3"
scrypt = "0.11.0"
serde = { version = "1.0.219", features = ["derive"] }
sha3 = "0.10.8"